In [39]:
import pandas as pd

In [2]:
# load tf list
fpath = "../resources/allTFs_hg38.txt"
tf_list = [x.strip() for x in open(fpath)]
print(f"{len(tf_list)=}")
tf_list[:10]

len(tf_list)=1892

['ZNF354C',
 'KLF12',
 'ZNF143',
 'ZIC2',
 'ZNF274',
 'SP2',
 'ZBTB7A',
 'BCL6B',
 'ZBTB49',
 'ZIC1']

In [3]:
def load_pathway(fpath):
    """
    Loads an Enrichr-like database file into a boolean DataFrame.

    Args:
        fpath (str): Path to the Enrichr-like database file.

    Returns:
        pandas.DataFrame: A boolean DataFrame where:
            - Index: Genes
            - Columns: Pathways
            - Values: True if the gene is in the pathway, False otherwise.
    """

    result = []
    with open(fpath,  encoding='utf-8') as f:
        for line in f:
            split_line = [x for x in line.strip().split('\t') if x]  # Remove empty strings directly

            row = {'label': split_line[0]}
            for gene in split_line[1:]:
                row[gene] = 1

            result.append(row)

    df = pd.DataFrame(result)
    df = df.fillna(0.0).set_index('label').astype(bool).T  # Chained operations for clarity
    return df

In [38]:
fpaths = {
    'panglao' : "../resources/PanglaoDB_Augmented_2021.txt",
    'tabula' : "../resources/Tabula_Sapiens.txt",
}

df = []

for key, fpath in fpaths.items():
    tab = load_pathway(fpath)
    tab = tab.astype(int)
    tab = tab.reset_index(names=['gene_name'])

    tab = pd.melt(tab, id_vars='gene_name')

    # drop non-markers
    tab = tab[tab['value'] > 0]
    tab['is_tf'] = tab['gene_name'].isin(tf_list)
    tab = tab.drop(columns='value')

    tab = tab.rename(columns={'label': 'cell_type'})

    tab['cell_type'] = tab['cell_type'].str.lower().str.replace(" ", "_")
    tab['source'] = key

    print(f"{tab.shape=}")
    df.append(tab)

df = pd.concat(df)
print(f"{df.shape=}")
df.head()

tab.shape=(24223, 4)
tab.shape=(46866, 4)
df.shape=(71089, 4)

  gene_name     cell_type  is_tf   source
0     GDF15  acinar_cells  False  panglao
1   RARRES2  acinar_cells  False  panglao
2    TM4SF4  acinar_cells  False  panglao
3     CELA1  acinar_cells  False  panglao
4       GCG  acinar_cells  False  panglao

In [34]:
df[df['cell_type'].str.contains('pluripotent', case=False, na=False)]['cell_type'].unique()

array(['pluripotent_stem_cells'], dtype=object)

In [35]:
cell_type_categories = {
    "fibroblast": [
        "fibroblasts",
        "bladder-fibroblast",
        "large_intestine-fibroblast",
        "lung-fibroblast",
        "pancreas-fibroblast",
        "prostate-fibroblast",
        "salivary_gland-fibroblast",
        "tongue-fibroblast",
        "uterus-fibroblast",
        "vasculature-fibroblast",
        "fat-fibroblast",
        "eye-fibroblast",
        "heart-fibroblast_of_cardiac_tissue",
        "mammary-fibroblast_of_breast"
    ],
    
    "myofibroblast": [
        "myofibroblasts",
        "bladder-myofibroblast_cell",
        "fat-myofibroblast_cell",
        "lung-myofibroblast_cell"
    ],
    
    "skeletal_muscle": [
        "muscle-skeletal_muscle_satellite_stem_cell",
        "skin-cell_of_skeletal_muscle",
    ],
    
    "myocyte": [
        "cardiomyocytes",
        "myocytes",
    ],
    
    "myoblast": [
        "myoblasts",
    ],
    
    "muscle": [
       'airway_smooth_muscle_cells',
       'pulmonary_vascular_smooth_muscle_cells',
       'smooth_muscle_cells',
       'vascular_smooth_muscle_cells',
       'bladder-smooth_muscle_cell',
       'lung-bronchial_smooth_muscle_cell',
       'lung-vascular_associated_smooth_muscle_cell',
       'muscle-capillary_endothelial_cell',
       'muscle-cd4-positive,_alpha-beta_t_cell',
       'muscle-cd8-positive,_alpha-beta_t_cell',
       'muscle-endothelial_cell_of_artery',
       'muscle-endothelial_cell_of_lymphatic_vessel',
       'muscle-endothelial_cell_of_vascular_tree', 
        'muscle-erythrocyte',
       'muscle-fast_muscle_cell', 
        'muscle-macrophage', 
        'muscle-mast_cell',
       'muscle-mature_nk_t_cell', 
        'muscle-mesenchymal_stem_cell',
       'muscle-pericyte_cell',
       'muscle-slow_muscle_cell', 
        'muscle-t_cell', 
        'muscle-tendon_cell',
       'thymus-fast_muscle_cell',
       'thymus-vascular_associated_smooth_muscle_cell',
       'vasculature-smooth_muscle_cell',
       'mammary-vascular_associated_smooth_muscle_cell',
       'uterus-vascular_associated_smooth_muscle_cell',
       'trachea-smooth_muscle_cell', 
        'tongue-tongue_muscle_cell',
       'prostate-smooth_muscle_cell', 
        'fat-smooth_muscle_cell',
       'skin-muscle_cell', 
        'heart-cardiac_muscle_cell',
       'heart-smooth_muscle_cell', 
        'lung-smooth_muscle_cell',
       'muscle-mesothelial_cell', 
        'muscle-smooth_muscle_cell', 
        'skin-smooth_muscle_cell'
    ],
    
    "ipsc": [
        "pluripotent_stem_cells",
    ]
}

# Reverse mapping: each cell type → its category
cell_type_to_category = {
    cell_type: category
    for category, cell_types in cell_type_categories.items()
    for cell_type in cell_types
}

df['category'] = df['cell_type'].map(cell_type_to_category)
df = df[df['category'].notna()]

print(df['category'].value_counts().to_string())

category
muscle             3964
fibroblast         1532
myofibroblast       401
myocyte             337
skeletal_muscle     200
myoblast            126
ipsc                112

In [36]:
outpath = "../resources/clean_marker_genes.csv"
df = df.reset_index(drop=True)
df.to_csv(outpath, index=False)
df.head()

  gene_name                   cell_type  is_tf   source category
0       LUM  airway_smooth_muscle_cells  False  panglao   muscle
1    COL1A1  airway_smooth_muscle_cells  False  panglao   muscle
2    COL5A2  airway_smooth_muscle_cells  False  panglao   muscle
3    COL5A1  airway_smooth_muscle_cells  False  panglao   muscle
4     FNDC1  airway_smooth_muscle_cells  False  panglao   muscle

In [37]:
df['is_tf'].value_counts()

is_tf
False    6234
True      438
Name: count, dtype: int64